### ISSUE TITLE
wpf ConnectToKnownDeviceAsync NullReferenceException

### ISSUE THREAD

**Issue by DrZhong** [newky2k/DSoft.System.BluetoothLe#14]
![image](https://user-images.githubusercontent.com/8085571/129502823-c19ff944-2c73-4db6-8d4e-c151d8c72797.png)

**Comment by newky2k** [comment]
@DrZhong Could you provide some further details, version of windows, project details(net core/net framework) etc?   Is the guid of the device correct or was the device not available?

thanks in advance

**Comment by newky2k** [comment]
@DrZhong  I have fixed this issue.  It appers the windows and android code didn't correctly throw an exception is the device could not be found.  

I've also added the optional parameter to " `ConnectToKnownDeviceAsync` (dontThrowExceptionOnNotFound) to disable throwing of the exception so that it will just return null if it cannot find the device.

Lastly i've updated all platforms to throw a new exception type `DeviceNotFoundException` when no device is found, so you can also catch that explicitly.
