### ISSUE TITLE
Access Denied When Executing "GetCharacteristicsAsync()" for Write Characteristic

### ISSUE THREAD

**Issue by MathiasHartner** [newky2k/DSoft.System.BluetoothLe#21]
Hi dude @newky2k ,

you are claiming that your library is supporting .NET Framework 4.6.1+.
Did you test your code running in a Win32 e.g. console application? If you did and it is working, maybe you can assist me because I have a serious problem when trying to get the write characteristics from our bluetooth LE device.

I show you inside your code what ALWAYS gives me `GattCommunicationStatus.AccessDenied`:
You are using: `var result = await NativeService.GetCharacteristicsAsync(BluetoothLE.CacheModeGetCharacteristics);` in your GattService (https://github.com/newky2k/DSoft.System.BluetoothLe/blob/master/DSoft.System.BluetoothLe/Service/Service.uwp.netcore.netf.cs).
There is another method you can call to directly get a known characteristic, so we use:
`var result = await NativeService.GetCharacteristicsForUuidAsync(uuid, BluetoothCacheMode.Cached);`
This works when getting the read characteristic but ALWAYS gives `result.Status == GattCommunicationStatus.AccessDenied` when getting the write characteristic.

If I use the same method as you (`NativeService.GetCharacteristicsAsync(BluetoothLE.CacheModeGetCharacteristics)`), it also fails with `GattCommunicationStatus.AccessDenied`.
But the call `var accessRequestResponse = await NativeService.RequestAccessAsync();` ALWAYS returns `DeviceAccessStatus.Allowed`.

I also asked those questions at [stackoverflow](https://stackoverflow.com/questions/71620883/ble-using-winrt-access-denied-when-executing-getcharacteristicsforuuidasync), within [discussions](https://github.com/shinyorg/shiny/discussions/961) of Shiny library and in the [Developer Community](https://developercommunity.visualstudio.com/t/BLE-Using-WinRT:-Access-Denied-When-Exec/1703310) of Visual Studio.

If you have ANY hint or advice, I would really appreciate it!

Kind regards,

Mathias Hartner

**Comment by newky2k** [comment]
@MathiasHartner  I'm sorrry your having an issue with this, it seems to be a known issue when using the WIndows Bluetooth stack via the Windows SDK with a non-UWP application.

I haven't created a .net framework specific sample, but i have had a .NET Core 3.1 and .NET 5 WPF application running with the library as well as a UWP application accessing both read and write characteristics.  I initially had the same issue with access denied when trying to implenent TI's OTAU, which is why i added the call to RequestAccessAsync() which solved the issue for me. 

I can see your point regarding the use of GetCharacteristicsAsync(BluetoothLE.CacheModeGetCharacteristics), to return all characteristics and then filter them, but this is a hold over from the original library i based our library on, so all platforms operate the same way.  It also doesn't seem especially efficient so I can look into an alternate implementation.

Could you provide some example code of how you are using our library to access the services characteristics, so i compare it with the working solution that I have.  

I'll also look to create a WPF based sample in this library for testing the functionality outside of the UWP sample already included.

**Comment by newky2k** [comment]
@MathiasHartner  As a work around have you tried just calling Service.GetCharacteristicsAsync() to load the characteristics from the bluetooth device and then filter them locally?

**Comment by MathiasHartner** [comment]
Thanks for your quick reply...You are right, that was the culprit!
You can only call ONCE for getting the characteristics, no matter if you call for all at once via `NativeService.GetCharacteristicsAsync(BluetoothLE.CacheModeGetCharacteristics)` or for a specific one via `NativeService.GetCharacteristicsForUuidAsync(uuid, BluetoothCacheMode.Cached)`.

Any subsequent calls will fail with `GattCommunicationStatus.AccessDenied`...
So my solution now is to retrieve all characteristics at once and filter them locally, like you proposed.

That did the trick! Anyways, this is so stupid...It wasted a lot of my time now!
I also do not need to set any `AccessPermission` via registry.

Thank you for your help and engagement, I will call out to you, if I stumble over another tricky situation, just to let you know.

PS: I am actually not using your library. We have a Xamarin app for Android and iOS using [Shiny.BluetoothLE](https://github.com/shinyorg/shiny/tree/16fc6ce1a39eae733b4bfa8d9d7288b4de015d8e/src/Shiny.BluetoothLE) since some time ago now. So our goal was to use as much code as possible of our bluetooth driver (it also supports classic BT) also for the .NET Framework implementation. I stumbled over your library when searching for a solution of my problem and was curious how you implemented it because you claimed it is also for .NET Framework 4.6.1+.
